### ISSUE TITLE
ValueError: the query contains a null character

### ISSUE THREAD

**Issue by AMJIYU** [rtcatc/Packer-Fuzzer#1]
[10:13:22] 正在检测目标响应状态中...
100%|█████████████████████████████████████████| 295/295 [00:59<00:00,  4.92it/s]
Traceback (most recent call last):
  File "PackerFuzzer.py", line 26, in <module>
    tt.check()
  File "PackerFuzzer.py", line 19, in check
    t.parseStart()
  File "/Users/*MASK*/Documents/pentest/Web/Packer-Fuzzer/lib/Controller.py", line 42, in parseStart
    DatabaseType(projectTag).insertTextFromDB(getTexts)
  File "/Users/*MASK*/Documents/pentest/Web/Packer-Fuzzer/lib/Database.py", line 244, in insertTextFromDB
    cursor.execute(sql)
ValueError: the query contains a null character

**Comment by rtcatc** [comment]
已加容错处理，之后便会更新。感谢您的反馈

**Comment by andyongxa** [comment]
相同问题,gif导致,config黑名单加入.gif临时解决了

**Comment by rtcatc** [comment]
> 相同问题，gif导致，config黑名单加入.gif临时解决了

是的，就是处理二进制文件导致的报错，下一版直接加容错

**Comment by guyueweige** [comment]
也碰到这个问题了，尝试加黑名单，还是不行

**Comment by rtcatc** [comment]
已在v1.0.3的更新中修复：https://github.com/rtcatc/Packer-Fuzzer/commit/91bcd1c25d8ce9cee06df639ed0a6666bbc458d2
若未成功修复，您只需要再回复此issue即可
