### ISSUE TITLE
sqlite3.OperationalError: near "type": syntax error

### ISSUE THREAD

**Issue by zhangtianqing98** [rtcatc/Packer-Fuzzer#14]
[!] 进入高级模式流程...
[10:25:42] 正在对JS文件做二次美化中...
[10:25:42] 正在提取API参数中，提取时间可能较长...
100%|███████████████████████████████████████████████████████████████████████████████████████████████| 24/24 [00:24<00:00,  1.00s/it]
Traceback (most recent call last):
  File "PackerFuzzer.py", line 26, in <module>
    tt.check()
  File "PackerFuzzer.py", line 19, in check
    t.parseStart()
  File "/home/explo1t/Desktop/Packer-Fuzzer/lib/Controller.py", line 48, in parseStart
    FuzzerParam(projectTag).FuzzerCollect()
  File "/home/explo1t/Desktop/Packer-Fuzzer/lib/FuzzParam.py", line 337, in FuzzerCollect
    cursor.execute(sql)
sqlite3.OperationalError: near "type": syntax error

**Comment by Oldman19** [comment]
+1我的也是这样

**Comment by 1104972454** [comment]
> +1我的也是这样

你好，方便加一下群讨论一下吗

**Comment by Feidao-fei** [comment]
+1

**Comment by hyccgit** [comment]
同上。。。。issuse  里面的问题到目前为止，我都遇到了一遍

**Comment by 1104972454** [comment]
> 同上。。。。issuse 里面的问题到目前为止，我都遇到了一遍

可以的话加个群一起讨论，或者将出bug的log和参数私发到1104972454@qq.com里

**Comment by rtcatc** [comment]
最新更新中已经修复，感谢您的反馈，若未成功修复您只需要回复此issue即可
