### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by chaserw** [rtcatc/Packer-Fuzzer#16]
[Err] local variable 'cursor' referenced before assignment
[21:57:26] 目标站点：http://114.*.*.98:9527
[21:57:26] 正在解析网页中...
Traceback (most recent call last):
  File "PackerFuzzer.py", line 26, in <module>
    tt.check()
  File "PackerFuzzer.py", line 19, in check
    t.parseStart()
  File "D:\Tool\Packer-Fuzzer\lib\Controller.py", line 30, in parseStart
    ParseJs(projectTag, self.url, self.options).parseJsStart()
  File "D:\Tool\Packer-Fuzzer\lib\ParseJs.py", line 154, in parseJsStart
    self.requestUrl()
  File "D:\Tool\Packer-Fuzzer\lib\ParseJs.py", line 60, in requestUrl
    conn = sqlite3.connect(os.sep.join(PATH.split('/')))
sqlite3.OperationalError: unable to open database file

Windows平台，python3.6，没有在tmp目录下创建子文件夹导致报错

**Comment by KpLi0rn** [comment]
您好 请更新一下项目 该问题已在最新版本中进行了修复
