### ISSUE TITLE
当提取API总数过少，自动开启暴力提取模式时的bug

### ISSUE THREAD

**Issue by zglaozhu** [rtcatc/Packer-Fuzzer#23]
命令
python PackerFuzzer.py -u https://www.umeng.com
错误信息
[02:27:11] 提取API总数过少，自动开启暴力提取模式
[02:27:11] 暴力提取文件：tmp\WPw65D_www.umeng.com\0VHodj.dpluscode
[02:27:11] 暴力提取文件：tmp\WPw65D_www.umeng.com\2Ikp6q.font_1515515_uf5ph5s0t7f.js
[02:27:11] 暴力提取文件：tmp\WPw65D_www.umeng.com\2YEila.iconfont
[02:27:11] 暴力提取文件：tmp\WPw65D_www.umeng.com\6tBbPc.js
[02:27:11] 暴力提取文件：tmp\WPw65D_www.umeng.com\8TDyss.js
[02:27:11] 暴力提取文件：tmp\WPw65D_www.umeng.com\9mQ1s8.jsonp.js
[02:27:11] 暴力提取文件：tmp\WPw65D_www.umeng.com\A9un24.js
[02:27:11] 暴力提取文件：tmp\WPw65D_www.umeng.com\CMQV9h.js
[02:27:11] 暴力提取文件：tmp\WPw65D_www.umeng.com\CWbauc.js
[02:27:11] 暴力提取文件：tmp\WPw65D_www.umeng.com\ESR1zj.js
[02:27:11] 暴力提取文件：tmp\WPw65D_www.umeng.com\eYEzO4.js
[02:27:11] 暴力提取文件：tmp\WPw65D_www.umeng.com\HAH9vn.index.js
[02:27:11] 暴力提取文件：tmp\WPw65D_www.umeng.com\i8kE0R.js
[02:27:11] 暴力提取文件：tmp\WPw65D_www.umeng.com\LoVUVM.alicarejs
[02:27:11] 暴力提取文件：tmp\WPw65D_www.umeng.com\lwuFEg.js
[02:27:11] 暴力提取文件：tmp\WPw65D_www.umeng.com\q9fgs1.js
[02:27:11] 暴力提取文件：tmp\WPw65D_www.umeng.com\R0eaG0.js
[02:27:11] 暴力提取文件：tmp\WPw65D_www.umeng.com\tp4JFn
[02:27:12] 暴力提取文件：tmp\WPw65D_www.umeng.com\wz4tkh.clue.js
[02:27:12] 暴力提取文件：tmp\WPw65D_www.umeng.com\XcfvvR.js
[02:27:12] 暴力提取文件：tmp\WPw65D_www.umeng.com\yZbonD.js
Traceback (most recent call last):
  File "PackerFuzzer.py", line 26, in <module>
    tt.check()
  File "PackerFuzzer.py", line 19, in check
    t.parseStart()
  File "C:\Users\admim\Desktop\工具\安全工具\信息收集\js信息收集\Packer-Fuzzer-master\lib\Controller.py", line 32, in parseStart
    Apicollect(projectTag).apireCoverStart()
  File "C:\Users\admim\Desktop\工具\安全工具\信息收集\js信息收集\Packer-Fuzzer-master\lib\ApiCollect.py", line 195, in apireCoverStart
    self.apiComplete()
  File "C:\Users\admim\Desktop\工具\安全工具\信息收集\js信息收集\Packer-Fuzzer-master\lib\ApiCollect.py", line 155, in apiComplete
    DatabaseType(self.projectTag).apiRecordToDB(filePath, completeApiPath)
  File "C:\Users\admim\Desktop\工具\安全工具\信息收集\js信息收集\Packer-Fuzzer-master\lib\Database.py", line 145, in apiRecordToDB
    jsFileID = DatabaseType(self.projectTag).getJsIDFromDB(localFileName, projectPath)
  File "C:\Users\admim\Desktop\工具\安全工具\信息收集\js信息收集\Packer-Fuzzer-master\lib\Database.py", line 135, in getJsIDFromDB
    jsFileID = cursor.fetchone()[0]  # 第一个即可
TypeError: 'NoneType' object is not subscriptable
![image](https://user-images.githubusercontent.com/31888299/99884629-bc2aa900-2c6a-11eb-964d-9dc1fa1bd73e.png)

**Comment by rtcatc** [comment]
![image](https://user-images.githubusercontent.com/15169833/99884691-6e914a80-2c30-11eb-939e-c79a7faf1c3e.png)
我这里没问题诶，我明天再看看

**Comment by rtcatc** [comment]
关于所有数据库写入错误，我们会在未来的几个更新之内将所有的数据改为base64编码之后再入库，从源头告别此类报错
感谢您的反馈，祝好！
