### ISSUE TITLE
关于 "Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] ..."的验证问题

### ISSUE THREAD

**Issue by metaStor** [rtcatc/Packer-Fuzzer#28]
当出现ssl证书验证的站：
![image](https://user-images.githubusercontent.com/43668218/105439619-24fcc480-5ca0-11eb-9b73-af79f45c1db3.png)

扫描会SSL验证报错：
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PackerFuzzer.py", line 26, in <module>
    tt.check()
  File "PackerFuzzer.py", line 19, in check
    t.parseStart()
  File "E:\Hacker\Tool\Packer-Fuzzer-1.2\lib\Controller.py", line 33, in parseStart
    ParseJs(projectTag, self.url, self.options).parseJsStart()
  File "E:\Hacker\Tool\Packer-Fuzzer-1.2\lib\ParseJs.py", line 167, in parseJsStart
    self.requestUrl()
  File "E:\Hacker\Tool\Packer-Fuzzer-1.2\lib\ParseJs.py", line 49, in requestUrl
    demo = requests.get(url=url, headers=headers,proxies=self.proxy_data).text
  File "F:\Anaconda\anaconda3\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "F:\Anaconda\anaconda3\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "F:\Anaconda\anaconda3\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "F:\Anaconda\anaconda3\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "F:\Anaconda\anaconda3\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='*****', port=8443): Max retries exceeded with url: /login (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1108)')))

建议增加全局忽略警告，例如（纯属建议哈，具体大佬看怎么改）：
在 lib/ParseJs.py中增加全局忽略警告：
**requests.packages.urllib3.disable_warnings()
ssl._create_default_https_context = ssl._create_unverified_context**

然后再请求处添加 verify=False：
demo = requests.get(url=url, headers=headers, proxies=self.proxy_data,**verify=False**).text

**Comment by rtcatc** [comment]
-f（--flag）

SSL连接安全选项，当为空时默认关闭状态，在此状态下将会阻止一切不安全的连接。若您希望忽略SSL安全状态，您可使用1命令开启，将会忽略一切证书错误，例如：-f 1；

**Comment by rtcatc** [comment]
感谢您的反馈，本工具支持使用-f 1命令开启全局证书校验忽略，若您的问题未能顺利解决，您可以随时回复此issue来开启本issue，谢谢您的支持！

**Comment by metaStor** [comment]
了解，谢谢大佬~
