### ISSUE TITLE
提取Api时出现错误

### ISSUE THREAD

**Issue by ZipperCode** [rtcatc/Packer-Fuzzer#39]
`[!] 检测到提取结果不准确，请输入新的BaseDir (使用逗号分隔)：other
Traceback (most recent call last):
  File "PackerFuzzer.py", line 26, in <module>
    tt.check()
  File "PackerFuzzer.py", line 19, in check
    t.parseStart()
  File "E:\Project\Git\Packer-Fuzzer\lib\Controller.py", line 47, in parseStart
    Apicollect(projectTag, self.options).apireCoverStart()
  File "E:\Project\Git\Packer-Fuzzer\lib\ApiCollect.py", line 204, in apireCoverStart
    self.apiComplete()
  File "E:\Project\Git\Packer-Fuzzer\lib\ApiCollect.py", line 162, in apiComplete
    DatabaseType(self.projectTag).apiRecordToDB(filePath, completeApiPath)
  File "E:\Project\Git\Packer-Fuzzer\lib\Database.py", line 145, in apiRecordToDB
    jsFileID = DatabaseType(self.projectTag).getJsIDFromDB(localFileName, projectPath)
  File "E:\Project\Git\Packer-Fuzzer\lib\Database.py", line 135, in getJsIDFromDB
    jsFileID = cursor.fetchone()[0]  # 第一个即可
TypeError: 'NoneType' object is not subscriptable`

**Comment by rtcatc** [comment]
谢谢您宝贵的意见，可否方便邮件我测试地址，方便我们定位异常成因： pocsir@qq.com / admin@hackinn.com
或者添加您微信：我朋友微信号: KpLi0rnSec
