### ISSUE TITLE
UnboundLocalError: local variable 'options' referenced before assignment

### ISSUE THREAD

**Issue by ViktorWkxStar** [rtcatc/Packer-Fuzzer#5]
Traceback (most recent call last):
  File "PackerFuzzer.py", line 26, in <module>
    tt.check()
  File "PackerFuzzer.py", line 19, in check
    t.parseStart()
  File "/root/tools/Packer-Fuzzer/lib/Controller.py", line 48, in parseStart
    FuzzerParam(projectTag).FuzzerCollect()
  File "/root/tools/Packer-Fuzzer/lib/FuzzParam.py", line 327, in FuzzerCollect
    for option in options:
UnboundLocalError: local variable 'options' referenced before assignment

**Comment by 1104972454** [comment]
这个问题我们已经排查出来了，是因为options这个局部变量在作用域范围外被使用了，我们会很快在下一个版本更新并排查这个错误，感谢你的反馈

**Comment by rtcatc** [comment]
已在v1.0.2的更新中修复：https://github.com/rtcatc/Packer-Fuzzer/commit/96475a2e3fb252ba14eeb789b42df29ecce7e2ed
若为成功修复，您只需要再回复此issue即可
