### ISSUE TITLE
UnboundLocalError: local variable 'whole_str' referenced before assignment

### ISSUE THREAD

**Issue by pigtt0** [rtcatc/Packer-Fuzzer#53]
[10:27:37] Extracting API parameters, which may take longer...
[Err]
Traceback (most recent call last):
  File "PackerFuzzer.py", line 26, in <module>
    tt.check()
  File "PackerFuzzer.py", line 19, in check
    t.parseStart()
  File "/root/Packer-Fuzzer/lib/Controller.py", line 63, in parseStart
    FuzzerParam(projectTag).FuzzerCollect()
  File "/root/Packer-Fuzzer/lib/FuzzParam.py", line 103, in FuzzerCollect
    for i in range(int((len(whole_str[0].split('§§§'))-1)/2)):
UnboundLocalError: local variable 'whole_str' referenced before assignment

**Comment by rtcatc** [comment]
感谢您的使用，可否方便提供更详细的信息例如log文件、目标站点等，谢谢！
若不方便公开发表，可发送至邮箱：admin@hackinn.com
