### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by AirSkye** [rtcatc/Packer-Fuzzer#7]
地址已发邮箱
[Err] unable to open database file
Traceback (most recent call last):
  File "PackerFuzzer.py", line 26, in <module>
    tt.check()
  File "PackerFuzzer.py", line 19, in check
    t.parseStart()
  File "D:\渗透工具\GitTools\Packer-Fuzzer\lib\Controller.py", line 31, in parseStart
    RecoverSpilt(projectTag,self.options).recoverStart()
  File "D:\渗透工具\GitTools\Packer-Fuzzer\lib\Recoverspilt.py", line 156, in recoverStart
    projectPath = DatabaseType(self.projectTag).getPathfromDB()
  File "D:\渗透工具\GitTools\Packer-Fuzzer\lib\Database.py", line 112, in getPathfromDB
    host = cursor.fetchone()[0]  # 第一个即可
TypeError: 'NoneType' object is not subscriptable

**Comment by rtcatc** [comment]
感谢您的反馈，正在排查中

**Comment by rtcatc** [comment]
为win环境下数据库路径问题，会在下一次更新中修复

**Comment by 974744840** [comment]
同样的问题，互联网的可以，内网的就出现报错了
[!] 外网连接失败，请检查当前网络状况或者代理情况
[Err] local variable 'cursor' referenced before assignment
[15:23:18] 目标站点：http://10.1.153.53:8088/**/login
[15:23:18] 正在解析网页中...
[15:23:18] 网页解析完毕，共发现14个JS文件
[Err] unable to open database file
Traceback (most recent call last):
  File "PackerFuzzer.py", line 26, in <module>
    tt.check()
  File "PackerFuzzer.py", line 19, in check
    t.parseStart()
  File "C:\Users\****\——Webpack\lib\Controller.py", line 31, in parseStart
    RecoverSpilt(projectTag,self.options).recoverStart()
  File "C:\Users\****\15——Webpack\lib\Recoverspilt.py", line 156, in recoverStart
    projectPath = DatabaseType(self.projectTag).getPathfromDB()
  File "C:\Users\****\lib\Database.py", line 112, in getPathfromDB
    host = cursor.fetchone()[0]  # 第一个即可
TypeError: 'NoneType' object is not subscriptable

**Comment by rtcatc** [comment]
已在v1.0.3的更新中修复：https://github.com/rtcatc/Packer-Fuzzer/commit/91bcd1c25d8ce9cee06df639ed0a6666bbc458d2
若未成功修复，您只需要再回复此issue即可
