### ISSUE TITLE
sqlite3.OperationalError: near "GET": syntax error

### ISSUE THREAD

**Issue by zhangtianqing98** [rtcatc/Packer-Fuzzer#9]
[19:33:53] 提取流程结束，初步提取API可能结果数：374
[19:33:53] 正在检测目标响应状态中...
100%|█████████████████████████████████████████████████████████████████████████████████████████████| 374/374 [01:15<00:00,  4.97it/s]
Traceback (most recent call last):
  File "PackerFuzzer.py", line 26, in <module>
    tt.check()
  File "PackerFuzzer.py", line 19, in check
    t.parseStart()
  File "/home/explo1t/Desktop/Packer-Fuzzer/lib/Controller.py", line 42, in parseStart
    DatabaseType(projectTag).insertTextFromDB(getTexts)
  File "/home/explo1t/Desktop/Packer-Fuzzer/lib/Database.py", line 244, in insertTextFromDB
    cursor.execute(sql)
sqlite3.OperationalError: near "GET": syntax error

**Comment by rtcatc** [comment]
您好，是sql写入失败造成的报错，方便私发一下对应目标站点吗？
admin # hackinn.com
谢谢

**Comment by zhangtianqing98** [comment]
> 您好，是sql写入失败造成的报错，方便私发一下对应目标站点吗？
> admin # hackinn.com
> 谢谢

好的，私发你的邮箱了

**Comment by ViktorWkxStar** [comment]
我也有同样问题...

**Comment by rtcatc** [comment]
已在v1.0.3的更新中修复：https://github.com/rtcatc/Packer-Fuzzer/commit/91bcd1c25d8ce9cee06df639ed0a6666bbc458d2
若未成功修复，您只需要再回复此issue即可
