### ISSUE TITLE
SSL 证书验证失败的问题

### ISSUE THREAD

**Issue by jjjxusbx** [rtcatc/Packer-Fuzzer#94]
```
[21:23:41] Parsing the page ...
Traceback (most recent call last):
  File "/miniconda3/envs/py310/lib/python3.10/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/miniconda3/envs/py310/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/miniconda3/envs/py310/lib/python3.10/site-packages/urllib3/connection.py", line 730, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/miniconda3/envs/py310/lib/python3.10/site-packages/urllib3/connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/miniconda3/envs/py310/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/miniconda3/envs/py310/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/miniconda3/envs/py310/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/miniconda3/envs/py310/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/miniconda3/envs/py310/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/miniconda3/envs/py310/lib/python3.10/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
  File "/miniconda3/envs/py310/lib/python3.10/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/miniconda3/envs/py310/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/miniconda3/envs/py310/lib/python3.10/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "/miniconda3/envs/py310/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.oit.edu.cn', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/tools/Packer-Fuzzer-1.4/PackerFuzzer.py", line 26, in <module>
    tt.check()
  File "/root/tools/Packer-Fuzzer-1.4/PackerFuzzer.py", line 19, in check
    t.parseStart()
  File "/root/tools/Packer-Fuzzer-1.4/lib/Controller.py", line 35, in parseStart
    ParseJs(projectTag, self.url, self.options).parseJsStart()
  File "/root/tools/Packer-Fuzzer-1.4/lib/ParseJs.py", line 174, in parseJsStart
    self.requestUrl()
  File "/root/tools/Packer-Fuzzer-1.4/lib/ParseJs.py", line 47, in requestUrl
    demo = requests.get(url=url, headers=headers,proxies=self.proxy_data).text
  File "/miniconda3/envs/py310/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/miniconda3/envs/py310/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/miniconda3/envs/py310/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/miniconda3/envs/py310/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/miniconda3/envs/py310/lib/python3.10/site-packages/requests/adapters.py", line 698, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.oit.edu.cn', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')))
```
使用 deno_vm 替代 node_vm2？依赖库的问题？

**Comment by rtcatc** [comment]
感谢您的反馈，本工具支持使用-f 1命令开启全局证书校验忽略，若您的问题未能顺利解决，您可以随时回复此issue来开启本issue，谢谢您的支持！
